#index:
#    path: /
#    controller: App\Controller\DefaultController::index

reservation:
  type: annotation
  resource: App\Controller\ReservationController
  prefix: /v1
  name_prefix: v1_
  defaults: {_format: json}